### ISSUE TITLE
can the script work from right to left?

### ISSUE THREAD

**Issue by eyalbin** [htdt/parallax#5]
Hi there,

This is an amazing plugin. is there a simple way to make slides move from right to left instead of left to right?

**Comment by htdt** [comment]
Currently slides are moving in both directions.

**Comment by eyalbin** [comment]
Thanks for your reply, 

I think you misunderstood me, what I meant was, that when you start in slide #1 scrolling to the next slide is always to the right (1st slide moving to the left).

Is there a way to make it the opposite direction? next slides will come from left side and first slide will move right.

**Comment by htdt** [comment]
Last slide can be shown in the beginning (and scroll will go right after). Take a look on processing initial hash in url, this code will help you to set last slide by default.

**Comment by eyalbin** [comment]
thank you very much :)
